name: Block unwanted (unconventional, fixup and squash) commits

on:
  pull_request:
    types: [opened, ready_for_review, reopened, synchronize]

permissions:
  contents: read

concurrency:
  group: block-unwanted-commits-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  block-unconventional-commits:
    name: Block unconventional commits

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          persist-credentials: false

      - uses: webiny/action-conventional-commits@8bc41ff4e7d423d56fa4905f6ff79209a78776c7 # v1.3.0
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  commit-message-check:
    if: github.event.pull_request.draft == false

    permissions:
      pull-requests: write
    name: Block fixup and squash commits

    runs-on: ubuntu-latest

    steps:
      - name: Run check
        uses: skjnldsv/block-fixup-merge-action@c138ea99e45e186567b64cf065ce90f7158c236a # v2
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
